[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "onepix"
version = "2.0.0"
description = "Core module of the ONE-PIX project"
authors = [
    { name = "Mathieu Ribes" },
    { name = "Gaspard Russias" },
    { name = "Antoine Fournier" }
]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["onepix*", "plugins*"]
