[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "numpy==1.22.4"
]
build-backend = "setuptools.build_meta"

[project]
name = "onepix"
version = "3.0.0"
description = "Core module of the ONE-PIX project"
authors = [
    { name = "Mathieu Ribes" },
    { name = "Gaspard Russias" },
    { name = "Antoine Fournier" }
]
requires-python = ">=3.8,<3.11"

# ✅ Dépendances PROD (versions compatibles entre elles)
dependencies = [
    "numpy==1.22.4",
    "pandas==2.0.3",
    "scikit-learn==1.0.2",
    "scikit-image==0.19.3",
    "scipy==1.13.1",
    "matplotlib==3.8.4",
    "opencv-python",
    "xarray==2023.1.0",
    "tifffile==2023.1.23.1",
    "customtkinter==5.2.0",
    "imutils==0.5.4",
    "screeninfo==0.8.1",
    "spectral==0.22.4",
    "seabreeze==2.0.2",
    "spyndex==0.3.0",
    "pyusb==1.2.1",
    "flask",
    "flask-socketio",
    "sympy==1.12",
    "orjson",
    "onepix-fis-common-function",
    "onepix-fouriersplit",
    "onepix-fouriershift",
    "onepix-stub-camera",
    "onepix-stub-spectrometer",
    "sphinx-rtd-theme"
    # "labelme==5.2.1"  # à activer si besoin
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=24.0.0",
    "ipython",
    "jupyterlab",
    "pip-tools"
]
docs = [
    "sphinx",
    "myst-parser",
    "sphinx-autoapi"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["onepix*", "plugins*"]
